baseURL = 'https://tea.xyz/'
languageCode = 'en-us'
title = 'Equitable Open-Source for Web3'

# menu links via config file

[menu]
  [[menu.main]]
    identifier = 'community'
    name = 'Community'
    title = 'community'
    url = '/#community'
    weight = 4
  [[menu.main]]
    identifier = 'blog'
    name = 'Blog'
    title = 'blog'
    url = 'https://medium.com/teaxyz'
    weight = 5